# Copyright Kusari, Inc. and contributors
apiVersion: v2
name: guac
description: A Helm chart for deploying GUAC to Kubernetes

maintainers:
  - name: kusaridev
    url: https://github.com/kusaridev/helm-charts
    email: guac-info@kusari.dev

type: application
version: 0.2.9
appVersion: "v0.5.2"

dependencies:
- name: nats
  version: "~0.19.12"
  repository: "https://nats-io.github.io/k8s/helm/charts/"
  condition: nats.enabled

# See s3 compatible storage config for MinIO at https://gocloud.dev/howto/blob/#s3
- name: minio
  version: "~5.0.15"
  repository: "https://charts.min.io/"
  condition: minio.enabled
