# Copyright Kusari, Inc. and contributors
# Licensed under the MIT license. See LICENSE file in the project root for details.
{{ if .Values.guac.graphqlServer.enabled }}
{{- if .Values.guac.graphqlServer.svcPorts }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.guac.graphqlServer.name }}
  labels:
    {{- include "guac.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.guac.graphqlServer.name }}
    app.kubernetes.io/component: {{ .Values.guac.graphqlServer.name }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "guac.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.guac.graphqlServer.name }}
    app.kubernetes.io/component: {{ .Values.guac.graphqlServer.name }}
    {{- include "custom.labels" . | nindent 4 }}
  ports:
  {{- range .Values.guac.graphqlServer.svcPorts }}
    - {{ . | toYaml | indent 6 | trim }}
  {{- end }}
{{- end }}
{{- end }}

{{ if .Values.guac.graphqlServer.enabled }}
{{- if .Values.guac.graphqlServer.svcPorts }}
{{ if .Values.guac.graphqlServer.service.createNodePortService }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.guac.graphqlServer.name }}-nodeport
  labels:
    {{- include "guac.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.guac.graphqlServer.name }}
    app.kubernetes.io/component: {{ .Values.guac.graphqlServer.name }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "guac.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.guac.graphqlServer.name }}
    app.kubernetes.io/component: {{ .Values.guac.graphqlServer.name }}
  ports:
  {{- range .Values.guac.graphqlServer.nodePortSvcPorts }}
    - {{ . | toYaml | indent 6 | trim }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}