# Copyright Kusari, Inc. and contributors
# Licensed under the MIT license. See LICENSE file in the project root for details.
{{ if .Values.guac.visualizer.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.guac.visualizer.name }}
{{- if .Values.guac.visualizer.annotations }}
  annotations:
{{ toYaml .Values.guac.visualizer.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "guac.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.guac.visualizer.name }}
    app.kubernetes.io/component: {{ .Values.guac.visualizer.name }}
spec:
  replicas:  {{ .Values.guac.visualizer.replicas }}
  selector:
    matchLabels:
      {{- include "guac.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ .Values.guac.visualizer.name }}
      app.kubernetes.io/component: {{ .Values.guac.visualizer.name }}
  template:
    metadata:
      labels:
        {{- include "guac.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Values.guac.visualizer.name }}
        app.kubernetes.io/component: {{ .Values.guac.visualizer.name }}
    spec:
      containers:
      # workaround the problem that next.config.js can't set gql-addr dynamically
      - name: nginx
        image: nginx:1.25.1
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: visualizer-proxy-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
            readOnly: true
      - name: {{ .Values.guac.visualizer.name }}
        {{- if .Values.guac.visualizer.image.digest }}
        image: "{{ .Values.guac.visualizer.image.repository }}@{{ .Values.guac.visualizer.image.digest }}"
        {{- else }}
        image: "{{ .Values.guac.visualizer.image.repository }}:{{ .Values.guac.visualizer.image.tag | default .Chart.AppVersion}}"
        {{- end }}
        imagePullPolicy: "{{ .Values.guac.visualizer.image.pullPolicy }}"
{{- if .Values.guac.visualizer.image.command }}
        command:
{{ toYaml .Values.guac.visualizer.image.command | indent 10 }}
{{- end }}
{{- if .Values.guac.visualizer.image.ports }}
        ports:
{{ toYaml .Values.guac.visualizer.image.ports | indent 10 }}
{{- end }}
        volumeMounts:
          - name: guac-config
            mountPath: /workspace/guac/guac.yaml
            subPath: guac.yaml
            readOnly: true
{{- if .Values.imagePullSecrets }}
{{- if or .Values.guac.common.env .Values.guac.visualizer.env }}
        env:
        {{- range $key, $value := .Values.guac.common.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}  
        {{- range $key, $value := .Values.guac.visualizer.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}  
{{- end }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
      volumes:
        - name: guac-config
          configMap:
            name: guac-cm
        - name: visualizer-proxy-config
          configMap:
            name: visualizer-proxy-cm
{{- end }}
{{- if .Values.guac.visualizer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.guac.visualizer.nodeSelector | indent 8 }}
{{- end }}
