name:  Helm Tests

on:
  push:
  pull_request:
    branches:
      - main

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Run helm unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git --version 0.4.1
          helm unittest charts/guac

      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
           version: 'v3.11.2'

      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.9'
          check-latest: true

      - name: Add Helm repos
        run: |
          helm repo add neo4j https://helm.neo4j.com/neo4j
          helm repo add nats https://nats-io.github.io/k8s/helm/charts
          helm repo add minio https://charts.min.io/

      - name: Set up chart-testing
        uses: helm/chart-testing-action@afea100a513515fbd68b0e72a7bb0ae34cb62aec # v2.3.1

      # TO-DO: make this step work to avoid creating cluster and run ct when charts are changed
      # - name: Run chart-testing (list-changed)
      #   id: list-changed
      #   run: |
      #     echo "::set-output name=changed::true"
      #     changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
      #     if [[ -n "$changed" ]]; then
      #       echo "::set-output name=changed::true"
      #     fi

      - name: Run chart-testing (lint)
        run: ct lint --all --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00 # v1.5.0
        # if: steps.list-changed.outputs.changed == 'true'

      - name: Set up kubectl
        uses: azure/setup-kubectl@901a10e89ea615cf61f57ac05cecdf23e7de06d8 # v3.2
        with:
           version: 'v1.26.0'
        id: install

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-testing (install)
        run: |
          kubectl create ns chart-testing
          ct install --all --helm-extra-args --timeout=600s --namespace chart-testing
        # if: steps.list-changed.outputs.changed == 'true'
